// frontend/src/components/MetricsDisplay.jsx
import { Card, CardBody, CardHeader, Table, TableHeader, TableColumn, TableBody, TableRow, TableCell } from '@heroui/react'

function formatTime(hours) {
  if (!hours) return '0h'
  if (hours < 24) return `${Math.round(hours)}h`
  const days = Math.round(hours / 24)
  return `${days}d`
}

export default function MetricsDisplay({ metrics, groupByAssignee }) {
  return (
    <div>
      {/* Main Metrics */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        <Card shadow="sm" radius="lg">
          <CardBody className="text-center py-6">
            <div className="flex justify-center mb-3">
              <div className="p-3 rounded-full bg-primary/10">
                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-primary">
                  <circle cx="12" cy="12" r="10" />
                  <polyline points="12 6 12 12 16 14" />
                </svg>
              </div>
            </div>
            <p className="text-sm font-medium text-default-500">Среднее время закрытия</p>
            <p className="text-3xl font-bold text-primary mt-1">
              {formatTime(metrics.average_close_time_hours)}
            </p>
          </CardBody>
        </Card>

        <Card shadow="sm" radius="lg">
          <CardBody className="text-center py-6">
            <div className="flex justify-center mb-3">
              <div className="p-3 rounded-full bg-secondary/10">
                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-secondary">
                  <polyline points="22 12 18 12 15 21 9 3 6 12 2 12" />
                </svg>
              </div>
            </div>
            <p className="text-sm font-medium text-default-500">Медианное время закрытия</p>
            <p className="text-3xl font-bold text-secondary mt-1">
              {formatTime(metrics.median_close_time_hours)}
            </p>
          </CardBody>
        </Card>

        <Card shadow="sm" radius="lg">
          <CardBody className="text-center py-6">
            <div className="flex justify-center mb-3">
              <div className="p-3 rounded-full bg-success/10">
                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-success">
                  <line x1="8" y1="6" x2="21" y2="6" />
                  <line x1="8" y1="12" x2="21" y2="12" />
                  <line x1="8" y1="18" x2="21" y2="18" />
                  <line x1="3" y1="6" x2="3.01" y2="6" />
                  <line x1="3" y1="12" x2="3.01" y2="12" />
                  <line x1="3" y1="18" x2="3.01" y2="18" />
                </svg>
              </div>
            </div>
            <p className="text-sm font-medium text-default-500">Всего задач</p>
            <p className="text-3xl font-bold text-success mt-1">
              {metrics.total_issues}
            </p>
          </CardBody>
        </Card>
      </div>

      {/* Assignee Breakdown */}
      {groupByAssignee && metrics.by_assignee && (
        <Card shadow="sm" radius="lg" className="mt-4">
          <CardHeader className="pb-0 pt-4 px-5">
            <h3 className="text-lg font-semibold">Метрики по исполнителям</h3>
          </CardHeader>
          <CardBody className="px-5 pb-5">
            <Table
              aria-label="Метрики по исполнителям"
              shadow="none"
              radius="md"
              isStriped
              classNames={{ th: 'text-xs font-semibold uppercase text-default-500' }}
            >
              <TableHeader>
                <TableColumn>Исполнитель</TableColumn>
                <TableColumn>Всего задач</TableColumn>
                <TableColumn>Среднее время</TableColumn>
                <TableColumn>Медианное время</TableColumn>
              </TableHeader>
              <TableBody>
                {Object.entries(metrics.by_assignee).map(([name, data]) => (
                  <TableRow key={name}>
                    <TableCell className="font-medium">{name}</TableCell>
                    <TableCell>{data.total_issues}</TableCell>
                    <TableCell>{formatTime(data.average_close_time_hours)}</TableCell>
                    <TableCell>{formatTime(data.median_close_time_hours)}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardBody>
        </Card>
      )}
    </div>
  )
}

// frontend/src/components/MetricsDisplay.vue
<template>
  <div>
    <!-- Main Metrics -->
    <v-row class="mb-4">
      <v-col cols="12" sm="6" md="4">
        <v-card class="elevation-2">
          <v-card-text>
            <div class="text-center">
              <v-icon size="40" color="primary" class="mb-2">mdi-speedometer</v-icon>
              <div class="text-h6">Среднее время закрытия</div>
              <div class="text-h4 font-weight-bold text-primary">
                {{ formatTime(metrics.average_close_time_hours) }}
              </div>
            </div>
          </v-card-text>
        </v-card>
      </v-col>

      <v-col cols="12" sm="6" md="4">
        <v-card class="elevation-2">
          <v-card-text>
            <div class="text-center">
              <v-icon size="40" color="secondary" class="mb-2">mdi-chart-line</v-icon>
              <div class="text-h6">Медианное время закрытия</div>
              <div class="text-h4 font-weight-bold text-secondary">
                {{ formatTime(metrics.median_close_time_hours) }}
              </div>
            </div>
          </v-card-text>
        </v-card>
      </v-col>

      <v-col cols="12" sm="6" md="4">
        <v-card class="elevation-2">
          <v-card-text>
            <div class="text-center">
              <v-icon size="40" color="success" class="mb-2">mdi-counter</v-icon>
              <div class="text-h6">Всего задач</div>
              <div class="text-h4 font-weight-bold text-success">
                {{ metrics.total_issues }}
              </div>
            </div>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>

    <!-- Assignee Breakdown (if enabled) -->
    <v-card v-if="groupByAssignee && metrics.by_assignee" class="mt-4">
      <v-card-title>Метрики по исполнителям</v-card-title>
      <v-card-text>
        <v-table>
          <thead>
            <tr>
              <th>Исполнитель</th>
              <th>Всего задач</th>
              <th>Среднее время</th>
              <th>Медианное время</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(data, name) in metrics.by_assignee" :key="name">
              <td>{{ name }}</td>
              <td>{{ data.total_issues }}</td>
              <td>{{ formatTime(data.average_close_time_hours) }}</td>
              <td>{{ formatTime(data.median_close_time_hours) }}</td>
            </tr>
          </tbody>
        </v-table>
      </v-card-text>
    </v-card>
  </div>
</template>

<script>
export default {
  name: 'MetricsDisplay',
  props: {
    metrics: {
      type: Object,
      required: true
    },
    groupByAssignee: {
      type: Boolean,
      default: false
    }
  },
  methods: {
    formatTime(hours) {
      if (!hours) return '0h'
      if (hours < 24) {
        return `${Math.round(hours)}h`
      }
      const days = Math.round(hours / 24)
      return `${days}d`
    }
  }
}
</script>

<style scoped>
</style>
